/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface InputBox {
    'label': string;
  }
  interface ProgressBar {
    'complete': number;
  }
}

declare global {


  interface HTMLInputBoxElement extends Components.InputBox, HTMLStencilElement {}
  var HTMLInputBoxElement: {
    prototype: HTMLInputBoxElement;
    new (): HTMLInputBoxElement;
  };

  interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {}
  var HTMLProgressBarElement: {
    prototype: HTMLProgressBarElement;
    new (): HTMLProgressBarElement;
  };
  interface HTMLElementTagNameMap {
    'input-box': HTMLInputBoxElement;
    'progress-bar': HTMLProgressBarElement;
  }
}

declare namespace LocalJSX {
  interface InputBox extends JSXBase.HTMLAttributes<HTMLInputBoxElement> {
    'label'?: string;
  }
  interface ProgressBar extends JSXBase.HTMLAttributes<HTMLProgressBarElement> {
    'complete'?: number;
  }

  interface IntrinsicElements {
    'input-box': InputBox;
    'progress-bar': ProgressBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


